### ISSUE TITLE
Problem with Travis and gh-pages

### ISSUE THREAD

**Issue by MiguelOrnia** [Arquisoft/viade_es1c#50]
This question has been posted on StackOverFlow to try to find a solution: https://es.stackoverflow.com/questions/337481/trouble-passing-tests-with-travis

**Comment by UO265308** [comment]
The same question has been posted on the StackOverflow english forum: https://stackoverflow.com/questions/60714860/dependency-error-with-the-bot-travis-while-running-tests-of-a-node-application-d

**Comment by MiguelOrnia** [comment]
Solved.
